package br.com.animation.util

object Constants {
    val FIRST_BACKGROUND_INTRO = "FIRST_BACKGROUND_INTRO"
    val SECOND_BACKGROUND_INTRO = "SECOND_BACKGROUND_INTRO"
    val THIRD_BACKGROUND_INTRO = "THIRD_BACKGROUND_INTRO"
}